pool:
  name: Hosted VS2017
steps:

- task: isaacabraham.fsharp-helpers-extension.5bfdd7ca-9bf4-40f7-b753-fd674e7ff85c.setCredentialManager@0
  displayName: 'Setup Paket Credential Manager'

- script: build.all.bat
  displayName: 'Build Libraries'

- script: |
   chdir /D src\app
   
   .paket\paket.exe restore
   if errorlevel 1 (
     exit /b %errorlevel%
   )
   
   ".paket/paket.exe" install 
   
   chdir /D CalculatorLibWeb.Function
   
   dotnet restore
   dotnet build
  displayName: 'Build Function App'

- script: |
   chdir /D src\app\CalculatorLibWeb.Function
   dotnet publish
  displayName: 'Create Function Publish'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)/src/app/CalculatorLibWeb.Function/bin/Debug/net472/publish'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/src/app/CalculatorLibWeb.Function/bin/Debug/net472/publish'
    includeRootFolder: false
    archiveFile: '$(Build.StagingDirectory)/$(Build.BuildId).zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: CalculatorLibWeb.Function'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: CalculatorLibWeb.Function

- task: isaacabraham.fsharp-helpers-extension.33416f37-5fe8-488d-a2aa-48f52e7a14f9.paketCredentialCleanup@0
  displayName: 'Cleanup Paket credential manager'