steps:
- task: AzureFunctionApp@1
  displayName: 'Azure Function App Deploy'
  inputs:
    azureSubscription: '6 - Month Plan'
    appType: functionApp
    appName: FunctionAppName
    package: '$(System.DefaultWorkingDirectory)/CalculatorLibWeb-CI/CalculatorLibWeb.Function/*.zip'
