// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("CalculatorLibWeb.Lib.dll")]
[assembly: AssemblyVersionAttribute("0.2.0.0")]
[assembly: AssemblyFileVersionAttribute("0.2.0.0")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyCopyrightAttribute("Copyright © CalculatorLibWeb 2019")]
[assembly: AssemblyCompanyAttribute("CalculatorLibWeb")]
[assembly: AssemblyDescriptionAttribute("Summary")]
[assembly: AssemblyTitleAttribute("CalculatorLibWeb.Lib.dll")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "CalculatorLibWeb.Lib.dll";
        internal const System.String AssemblyVersion = "0.2.0.0";
        internal const System.String AssemblyFileVersion = "0.2.0.0";
        internal const System.Boolean ComVisible = false;
        internal const System.String AssemblyCopyright = "Copyright © CalculatorLibWeb 2019";
        internal const System.String AssemblyCompany = "CalculatorLibWeb";
        internal const System.String AssemblyDescription = "Summary";
        internal const System.String AssemblyTitle = "CalculatorLibWeb.Lib.dll";
    }
}
